/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.15 ../public/fit_guy.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/fit_guy.glb')
  const { actions } = useAnimations(animations, group)
  console.log("🚀 ~ file: Fit_guy.jsx:13 ~ Model ~ actions:", actions);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Арматура">
          <primitive object={nodes.Bone24} />
          <skinnedMesh name="Body" geometry={nodes.Body.geometry} material={materials.Skin} skeleton={nodes.Body.skeleton} />
          <skinnedMesh name="Hair" geometry={nodes.Hair.geometry} material={materials.Hair} skeleton={nodes.Hair.skeleton} />
          <skinnedMesh name="Shorts" geometry={nodes.Shorts.geometry} material={materials.Shorts} skeleton={nodes.Shorts.skeleton} />
          <skinnedMesh name="T-shirt" geometry={nodes['T-shirt'].geometry} material={materials['T-shirt']} skeleton={nodes['T-shirt'].skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fit_guy.glb')
